# Generated by Django 5.2.1 on 2025-05-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('focus_area', models.CharField(blank=True, help_text='e.g., Education, Environment, Health', max_length=100)),
                ('description_short', models.TextField(help_text='A brief summary for the project card.')),
                ('description_long', models.TextField(blank=True, help_text="Detailed information for the project's own page.", null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Planned', 'Planned')], default='Planned', max_length=50)),
                ('is_signature_project', models.BooleanField(default=False, help_text='Check if this is one of the main signature projects.')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from title, or provide a custom one.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
