# Generated by Django 5.2.1 on 2025-05-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='e.g., President, Secretary, Member', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short biography or role description.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Profile picture (optional).', null=True, upload_to='team_photos/')),
                ('email', models.EmailField(blank=True, help_text='Contact email (optional).', max_length=254, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance (e.g., 0 for President, 1 for VP, then alphabetically or by join date).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
