# Generated by Django 5.2.1 on 2025-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='official_term_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the starting year of the term this person is an official (e.g., 2024 for the 2024-25 term). Leave blank if not an official for a specific displayed term or for general members.', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Order of appearance for officials (e.g., 0 for President, 1 for VP). General members can have a higher number or default.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(help_text='e.g., President, Secretary, Member(s).', max_length=100),
        ),
    ]
