# Generated by Django 5.2.1 on 2025-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teammember_official_term_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='A representative image for the project (optional).', null=True, upload_to='project_images/'),
        ),
    ]
