# Generated by Django 5.2.1 on 2025-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown/Not Specified')], default='Unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone number (e.g., +91-9876543210) (optional).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='joining_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the member joined the Rotaract club (e.g., 2023).', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='rotaract_id',
            field=models.CharField(blank=True, help_text='Rotaract International ID (if applicable).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='official_term_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the starting year of the term this person is an official (e.g., 2024 for the 2024-25 term). Leave blank if not an official or for general members.', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(help_text="e.g., President, Secretary, Member. For general members, can be 'Member'.", max_length=100),
        ),
    ]
